"""empty message

Revision ID: 0ed18f2da672
Revises: c618fe9a4e9b
Create Date: 2024-07-15 23:49:18.660546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed18f2da672'
down_revision = 'c618fe9a4e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_apperences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_apperences_episodie_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'episode', ['episode_id'], ['id'])
        batch_op.drop_column('episodie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_apperences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episodie_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_apperences_episodie_id_fkey', 'episode', ['episodie_id'], ['id'])
        batch_op.drop_column('episode_id')

    # ### end Alembic commands ###
